export default {
    'default_error': 'Unknown error.',
    'unknown_error': 'Unknown error.',
    'unknown_message_type': 'Unknown message type.',
    'no_response_from_server': 'No response from server.',
    'registration_successful': 'Registration successful!',
    'no_user_with_such_username': 'No user with such username.',
    'login_failed': 'Login failed.',
    'incorrect_username_or_password': 'Incorrect username or password.',
    'login_successful': 'Login successful!',
    'incorrect_data': 'Incorrect data.',
    'has_signer_with_such_public_key_or_label': 'Has signer with such public key or label.',
    'has_user_with_such_username': 'Has user with such username.',
    'added_signer': 'Added signer!',
    'added_txn_family': 'Added transaction family!',
    'has_transaction_family_with_such_prefix_or_label': 'Has transaction family with such prefix or label.',
    'updated_transaction_family': 'Updated transaction family!',
    'updated_signer': 'Updated signer!',
    'action_unallowed': 'Action is unallowed.',
    'no_session_try_to_sign_in_again': 'No session. Try signing in again.',
    'invalid_protos_set': 'Invalid protos set.',
    'protos_uploaded_and_processed_successfully': 'Protos uploaded and processed successfully!',
    'no_files_received': 'No files received.',
    'updated_rules_successfully': 'Rules updated!',
    'modified_setting_successfully': 'Settings modified!',
    'user_modified_successfully': 'Account modified!',
    'added_account': 'Account added!',
    'invalid_param_value': 'Invalid or missing field.',
    'upserted_custom_menu_item': 'Upserted custom menu item!',
}
