version: '3.6'

services:

  settings-tp-0:
    image: hyperledger/sawtooth-settings-tp:chime
    container_name: sawtooth-settings-tp-0
    depends_on:
      - validator-0
    entrypoint: settings-tp -vv -C tcp://validator-0:4004

  validator-0:
    image: hyperledger/sawtooth-validator:chime
    container_name: sawtooth-validator-0
    expose:
      - 4004
    ports:
      - "4004:4004"
    # start the validator with an empty genesis batch
    entrypoint: "bash -c \"\
        sawadm keygen && \
        sawtooth keygen my_key && \
        sawset genesis -k /root/.sawtooth/keys/my_key.priv && \
        sawset proposal create \
          -k /root/.sawtooth/keys/my_key.priv \
          sawtooth.consensus.algorithm.name=Devmode \
          sawtooth.consensus.algorithm.version=0.1 \
          -o config.batch && \
        sawadm genesis config-genesis.batch config.batch && \
        sawtooth-validator -vv \
          --endpoint tcp://validator-0:8800 \
          --bind component:tcp://eth0:4004 \
          --bind network:tcp://eth0:8800 \
          --bind consensus:tcp://eth0:5050 \
        \""

  devmode-engine:
    image: hyperledger/sawtooth-devmode-engine-rust:chime
    container_name: sawtooth-devmode-engine-rust-default
    depends_on:
      - validator-0
    entrypoint: devmode-engine-rust -C tcp://validator-0:5050

  rest-api-0:
    image: hyperledger/sawtooth-rest-api:chime
    container_name: sawtooth-rest-api-0
    ports:
      - "8008:8008"
    depends_on:
      - validator-0
    entrypoint: sawtooth-rest-api -C tcp://validator-0:4004 --bind rest-api-0:8008

  shell:
    image: hyperledger/sawtooth-shell:chime
    container_name: sawtooth-shell-default
    depends_on:
      - rest-api-0
    command: |
      bash -c "
        if [ ! -e /root/.sawtooth/keys/my_key.priv ]; then
          sawtooth keygen
          tail -f /dev/null
        fi
      "

# --------=== audit transaction processor ===--------

  audit-tp-0:
    image: audit-tp:latest
    container_name: audit-tp-0
    environment:
      - NODE=0
      - TP_FAMILY=AuditSystem
      - TP_VERSION=1.0
    depends_on:
      - validator-0
    build:
      context: ./tp
      dockerfile: ../Dockerfile

# --------=== blockchain client ===--------

  client-0:
    hostname: node0
    image: client
    container_name: client-0
    expose:
      - 4000
    ports:
      - "4000:4000"
    environment:
      - NODE=0
      - CLIENT_PORT=4000
      - TP_FAMILY=AuditSystem
      - TP_VERSION=1.0
    depends_on:
      - rest-api-0
    build:
      context: ./client
      dockerfile: ../Dockerfile

# --------=== blockchain interface ===--------

  interface-0:
    image: interface
    container_name: interface-0
    environment:
      - NODE=0
      - DATABASE_USER=gaar
      - DATABASE_PASSWORD=gaar
      - DATABASE_SERVER=192.168.100.9
      - DATABASE_NAME=mybank
    depends_on:
      - client-0
    build:
      context: ./interface
      dockerfile: ../Dockerfile

# --------=== Grafana ===--------

  sawtooth-stats-grafana:
    container_name: sawtooth-stats-grafana
    build:
      context: ./grafana
    expose:
      - 3000
    ports:
      - 3000:3000
    depends_on:
      - influxdb

# --------=== Influxdb ===--------

  influxdb:
    image: influxdb:1.8-alpine
    container_name: sawtooth-stats-influxdb
    environment:
      - INFLUXDB_DB=metrics
      - INFLUXDB_HTTP_AUTH_ENABLED=true
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
      - INFLUXDB_USER=lrdata
      - INFLUXDB_USER_PASSWORD=lrdata
    expose:
      - 8086
    ports:
      - "8086:8086"

# -------------=== Telegraf ===-------------

  telegraf:
    container_name: telegraf
    build:
      context: ./telegraf
    ports:
      - 8125:8125
      - 8092:8092
      - 8094:8094

# --------=== frontend client ===--------

  frontend:
    image: frontend
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - client-0
    build:
      context: ./frontend
