version: '3.6'

volumes:
  pbft-shared:
  blockchain_data:

networks:
  _network:
    external:
      name: audit_network

services:

# -------------=== rest api ===-------------

  rest-api-3:
    image: hyperledger/sawtooth-rest-api:chime
    container_name: sawtooth-rest-api-3
    expose:
      - 8008
    volumes:
      - ./pbft-shared:/pbft-shared
    command: |
      bash -c "
        cp /pbft-shared/config/rest_api.toml /etc/sawtooth/rest_api.toml
        sawtooth-rest-api \
          --connect tcp://validator-3:4004 \
          --bind rest-api-3:8008
      "
    networks:
      - _network
    stop_signal: SIGKILL

# -------------=== settings tp ===-------------

  settings-tp-3:
    image: hyperledger/sawtooth-settings-tp:chime
    container_name: sawtooth-settings-tp-3
    expose:
      - 4004
    command: settings-tp -C tcp://validator-3:4004
    networks:
      - _network
    stop_signal: SIGKILL

# -------------=== validators ===-------------

  validator-3:
    image: hyperledger/sawtooth-validator:chime
    container_name: sawtooth-validator-3
    expose:
      - 4004
      - 5050
      - 8800
    volumes:
      - ./pbft-shared:/pbft-shared
      - blockchain_data:/var/lib/sawtooth
    command: |
      bash -c "
        cp /pbft-shared/config/validator.toml /etc/sawtooth/validator.toml
        if [ -e /pbft-shared/validators/validator-3.priv ]; then
         cp /pbft-shared/validators/validator-3.pub /etc/sawtooth/keys/validator.pub
         cp /pbft-shared/validators/validator-3.priv /etc/sawtooth/keys/validator.priv
        fi &&
        if [ ! -e /etc/sawtooth/keys/validator.priv ]; then
         sawadm keygen
         cp /etc/sawtooth/keys/validator.pub /pbft-shared/validators/validator-3.pub
         cp /etc/sawtooth/keys/validator.priv /pbft-shared/validators/validator-3.priv
        fi &&
        if [ -e /pbft-shared/user_keys/my_key-3.priv ]; then
          mkdir -p /root/.sawtooth/keys || true
          cp /pbft-shared/user_keys/my_key-3.pub /root/.sawtooth/keys/my_key.pub
          cp /pbft-shared/user_keys/my_key-3.priv /root/.sawtooth/keys/my_key.priv
        fi &&
        if [ ! -e /root/.sawtooth/keys/my_key.priv ]; then
          sawtooth keygen my_key
          cp /root/.sawtooth/keys/my_key.pub /pbft-shared/user_keys/my_key-3.pub
          cp /root/.sawtooth/keys/my_key.priv /pbft-shared/user_keys/my_key-3.priv
        fi &&
        sawtooth-validator -vv \
          --endpoint tcp://validator-3:8800 \
          --bind component:tcp://eth0:4004 \
          --bind consensus:tcp://eth0:5050 \
          --bind network:tcp://eth0:8800 \
          --scheduler parallel \
          --peering static \
          --maximum-peer-connectivity 10000 \
          --peers tcp://validator-0:8800 \
          --peers tcp://validator-1:8800 \
          --peers tcp://validator-2:8800
      "
    networks:
      - _network

# -------------=== pbft engines ===-------------

  pbft-3:
    image: hyperledger/sawtooth-pbft-engine:chime
    container_name: sawtooth-pbft-engine-3
    command: pbft-engine -vv --connect tcp://validator-3:5050
    networks:
      - _network
    stop_signal: SIGKILL

# --------=== audit transaction processor ===--------

  audit-tp-3:
    image: audit-tp:latest
    container_name: audit-tp-3
    environment:
      - NODE=3
      - TP_FAMILY=AuditSystem
      - TP_VERSION=1.0
    depends_on:
      - validator-3
    build:
      context: ./tp
      dockerfile: ../Dockerfile
    networks:
      - _network

# --------=== blockchain client ===--------

  client-3:
    hostname: node3
    image: client
    container_name: client-3
    expose:
      - 4000
    ports:
      - "4000:4000"
    environment:
      - NODE=3
      - CLIENT_PORT=4000
      - TP_FAMILY=AuditSystem
      - TP_VERSION=1.0
    depends_on:
      - rest-api-3
    build:
      context: ./client
      dockerfile: ../Dockerfile
    networks:
      - _network

# --------=== blockchain interface ===--------

  interface-3:
    image: interface
    container_name: interface-3
    environment:
      - NODE=3
      - DATABASE_USER=SA
      - DATABASE_PASSWORD=GaarGaar1234
      - DATABASE_SERVER=10.142.0.2
      - DATABASE_NAME=mybank
    depends_on:
      - client-0
    build:
      context: ./interface
      dockerfile: ../Dockerfile

# --------=== blockchain interface ===--------

  interface-3:
    image: interface
    container_name: interface-3
    environment:
      - NODE=3
      - DATABASE_USER=SA
      - DATABASE_PASSWORD=GaarGaar1234
      - DATABASE_SERVER=10.142.0.5
      - DATABASE_NAME=mybank
    depends_on:
      - client-3
    build:
      context: ./interface
      dockerfile: ../Dockerfile
    networks:
      - _network
