#!/usr/bin/env bash
echo Swarm Join...
sudo docker swarm join --token $(cat /vagrant/token) $10:2377 --advertise-addr $1$2
echo Docker Pull...
sudo docker-compose -f /vagrant/docker/docker-compose-$2.yaml pull -d